### ISSUE TITLE
Missing src Directory in react-native-launcher-kit During Codegen Schema Generation

### ISSUE THREAD

**Issue by lucasheidebrecht** [louaySleman/react-native-launcher-kit#12]
**Describe the bug**
When trying to build the project, the task react-native-launcher-kit:generateCodegenSchemaFromJavaScript fails with an error indicating that the src directory is missing in the node_modules/react-native-launcher-kit package.

**To Reproduce**
1. Create a React Native project.
2. Add the react-native-launcher-kit package.
3. Attempt to build or run the project.
4. Observe the error during the generateCodegenSchemaFromJavaScript step.

**Expected behavior**
The project should build successfully, and the react-native-launcher-kit package should generate the necessary schema without errors.

**Smartphone (please complete the following information):**
 - Device: samsung s23
 - OS: android
 - android sdk 34
 - node version Node.js v18.20.5

**Error Code:**
> Task :react-native-launcher-kit:generateCodegenSchemaFromJavaScript FAILED
node:internal/fs/utils:356
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '..\src'
    at Object.lstatSync (node:fs:1666:3)
    at C:\Users\lucash\Desktop\Proyectos\app-instaler\node_modules\@react-native\codegen\lib\cli\combine\combine-js-to-schema.js:108:15
    at Array.flatMap (<anonymous>)
    at expandDirectoriesIntoFiles (C:\Users\lucash\Desktop\Proyectos\app-instaler\node_modules\@react-native\codegen\lib\cli\combine\combine-js-to-schema.js:107:6)
    at combineSchemasInFileList (C:\Users\lucash\Desktop\Proyectos\app-instaler\node_modules\@react-native\codegen\lib\cli\combine\combine-js-to-schema.js:123:28)
    at combineSchemasInFileListAndWriteToFile (C:\Users\lucash\Desktop\Proyectos\app-instaler\node_modules\@react-native\codegen\lib\cli\combine\combine-js-to-schema.js:142:20)
    at Object.<anonymous> (C:\Users\lucash\Desktop\Proyectos\app-instaler\node_modules\@react-native\codegen\lib\cli\combine\combine-js-to-schema-cli.js:76:1)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  errno: -4058,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '..\\src'
}

**Comment by numblock** [comment]
duplicate of https://github.com/louaySleman/react-native-launcher-kit/issues/9 ?

**Comment by tuposilwe** [comment]
rename **module** to **src** in node_modules/react-native-launcher-kit. this worked for me
